// <auto-generated />
using System;
using Fiap.Vacina.Facil.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Vacina.Facil.Migrations
{
    [DbContext(typeof(VacinaFacilContext))]
    partial class VacinaFacilContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Aviso", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("AvisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvisoId"));

                    b.Property<DateTime>("DataAviso")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Aviso");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Ds_Descrição");

                    b.HasKey("ClienteId", "AvisoId");

                    b.ToTable("T_VacinaFacil_Aviso");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SituacaoCliente")
                        .HasColumnType("int")
                        .HasColumnName("Situacao");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("ClienteId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("T_VacinaFacil_Cliente");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Dependente", b =>
                {
                    b.Property<int>("DependenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependenteId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DependenteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("T_VacinaFacil_Dependente");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnderecoId"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SituacaoEndereco")
                        .HasColumnType("int")
                        .HasColumnName("Situacao");

                    b.HasKey("EnderecoId");

                    b.ToTable("T_VacinaFacil_End");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Fabricante", b =>
                {
                    b.Property<int>("FabricanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabricanteId"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VaccineId")
                        .HasColumnType("int");

                    b.HasKey("FabricanteId");

                    b.HasIndex("VaccineId");

                    b.ToTable("T_VacinaFacil_Fabricante");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Vaccine", b =>
                {
                    b.Property<int>("VaccineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccineId"));

                    b.Property<string>("Composicao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DoseVacina")
                        .HasColumnType("int");

                    b.Property<int>("Intervalo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VaccineId");

                    b.ToTable("T_VacinaFacil_Vaccine");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Aviso", b =>
                {
                    b.HasOne("Fiap.Vacina.Facil.Models.Cliente", "Cliente")
                        .WithMany("Avisos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Cliente", b =>
                {
                    b.HasOne("Fiap.Vacina.Facil.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Dependente", b =>
                {
                    b.HasOne("Fiap.Vacina.Facil.Models.Cliente", "Cliente")
                        .WithMany("Dependentes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Fabricante", b =>
                {
                    b.HasOne("Fiap.Vacina.Facil.Models.Vaccine", null)
                        .WithMany("Fabricantes")
                        .HasForeignKey("VaccineId");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Cliente", b =>
                {
                    b.Navigation("Avisos");

                    b.Navigation("Dependentes");
                });

            modelBuilder.Entity("Fiap.Vacina.Facil.Models.Vaccine", b =>
                {
                    b.Navigation("Fabricantes");
                });
#pragma warning restore 612, 618
        }
    }
}
